apiVersion: v1
kind: Secret
metadata:
    name: secret
    annotations:
        some.domain.com/foo: bar
stringData:
    foo: ENC[AES256_GCM,data:5Czb,iv:9pu0tjIJz5plxRZ0XAs1DJCZcO/vOdQWavPmrX1xOb8=,tag:/QYxcDIvpVKhHCltEAAtPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ks0a8wkcdt74jp9l2chgny8e2pnjqta7rdwam4ju4ceqervn5ulq26q0wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucFBjTmZVaGtIeDlUay9r
            RkpCaFpRNkZXVkI1NnVBMTFRK2E0RTh2RVNnCjE3TVljWlJ5ckVsUVpFQ3BTaE9B
            QWlUNGpZeUszWEtsS2VmM2NWeFBxbWMKLS0tIDFVL1JCWnlKWi9SL3RSamgxZDln
            QVNhbnBQZFhTMjMwbC9WM1o1Q09oZzgK1n/KJheKDMFu+bStbiyR5oG0uxoJ0Wv7
            q7lENLefcYv6aVlq6A5T3+ixA3D7D+lGXfsmrWWVxdxkW6T4eeGFFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-16T09:40:57Z"
    mac: ENC[AES256_GCM,data:04fF153myOIWX16XTqMR6q+BAxvKMXPI9nYsISzgvt6gimtUR/WWFjKq+Zi8WXKAXEd3iVI7xnC/9oPchi1th9DSWEyN3CejaTmb3uJmzBNdoAhDMlvVYeVgbYxq7dJ+d8widf+RWiCw0DxmwZGgiLX+KcOHOrwklN0K+Mc7G8s=,iv:bgepgqlGEk4rQgArq1/Qois29qQu4/QztlPsK1n3QRA=,tag:oxJ3GjtZiRhErZUS5DYmfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
